services:
  - type: web
    name: product-hunt-backend
    env: python
    buildCommand: pip install -r scraper/requirements.txt
    startCommand: uvicorn scraper.search_products:app --host 0.0.0.0 --port 10000
    plan: free
    region: oregon
    envVars:
      - key: PINECONE_API_KEY
        value: your-pinecone-key
      - key: PINECONE_INDEX_NAME
        value: ph-products-index
